services:
  - type: web
    name: warehouse-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: "8260246769:AAHP0OOyCv_JrOWhVRsD0rsImN7REvhFUz4"
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: "padval"
      - key: NODE_ENV
        value: "production"
databases:
  - name: warehouse-db
    databaseName: padval
    user: postgres
