<<<<<<< HEAD
# Exported from Render on 2026-03-04T01:57:04Z
version: "1"
services:
- type: web
  name: termux-project-1
  runtime: node
  repo: https://github.com/Sardor0485/termux-project
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node app.js
  autoDeployTrigger: commit
=======
# Render.yaml Configuration for Node.js Application

# The name of the service
service:
  name: NodeApp
  type: web

# The environment for the service
env:
  type: node

# The build settings
build:
  env:
    NODE_VERSION: "14"

# The start command to run the application
startCommand: npm start

# Specify the resources for the service
instances: 1
>>>>>>> fd25f861b56834e97c809ee346fbd7804211ff14
