CREATE DATABASE IF NOT EXISTS sklad CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE sklad;

CREATE TABLE IF NOT EXISTS items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kod VARCHAR(100) NOT NULL,
  nomi VARCHAR(255) NOT NULL,
  rangi VARCHAR(100),
  soni INT DEFAULT 0,
  qator VARCHAR(10),
  stellaj VARCHAR(10),
  image VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NULL,
  item_name VARCHAR(255) NULL,
  type ENUM('kirim','chiqim') NOT NULL,
  amount INT NOT NULL,
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE SET NULL
);
